In [2]:
import pandas as pd

In [8]:
df = pd.read_csv('./data/weather.csv')

In [9]:
df.head()

,queryCost,latitude,longitude,resolvedAddress,address,timezone,tzoffset,feelslikemax,feelslikemin,feelslike,...,icon,stations,distance,latitude.1,longitude.1,useCount,id,name,quality,contribution
0,1,32.5625,107.450,"32.5625,107.45","32.5625,107.45",Asia/Shanghai,8.0,90.7,76.0,82.7,...,partly-cloudy-day,57127099999,68354.0,33.067,107.033,0,57127099999,"HANZHONG, CH",67,0.0
1,1,32.5625,107.450,"32.5625,107.45","32.5625,107.45",Asia/Shanghai,8.0,90.7,76.0,82.7,...,partly-cloudy-day,57237099999,77810.0,32.067,108.033,0,57237099999,"WANYUAN, CH",65,0.0
2,1,45.4200,-122.663,"45.42,-122.663","45.42,-122.663",America/Los_Angeles,-8.0,41.4,23.7,35.0,...,rain,72695994281,20805.0,45.249,-122.769,0,72695994281,"AURORA STATE AIRPORT, OR US",100,0.0
3,1,45.4200,-122.663,"45.42,-122.663","45.42,-122.663",America/Los_Angeles,-8.0,41.4,23.7,35.0,...,rain,72698024229,20018.0,45.596,-122.609,0,72698024229,"PORTLAND INTERNATIONAL AIRPORT, OR US",100,0.0
4,1,45.4200,-122.663,"45.42,-122.663","45.42,-122.663",America/Los_Angeles,-8.0,41.4,23.7,35.0,...,rain,72791894298,22358.0,45.621,-122.657,0,72791894298,"VANCOUVER PEARSON AIRPORT, WA US",100,0.0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38252 entries, 0 to 38251
Data columns (total 40 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   queryCost        38252 non-null  int64
 1   latitude         38252 non-null  float64
 2   longitude        38252 non-null  float64
 3   resolvedAddress  38252 non-null  object
 4   address          38252 non-null  object
 5   timezone         38252 non-null  object
 6   tzoffset         38252 non-null  float64
 7   feelslikemax     38237 non-null  float64
 8   feelslikemin     38237 non-null  float64
 9   feelslike        38237 non-null  float64
 10  dew              38203 non-null  float64
 11  humidity         38203 non-null  float64
 12  precip           38252 non-null  float64
 13  precipprob       0 non-null      float64
 14  precipcover      38252 non-null  float64
 15  preciptype       0 non-null      float64
 16  snow             7941 non-null   float64
 17  snowdepth        8944 non-null   float64
 18  windgust         20334 non-null  float64
 19  windspeed        38222 non-null  float64
 20  winddir          37236 non-null  float64
 21  pressure         34158 non-null  float64
 22  cloudcover       38252 non-null  float64
 23  visibility       38023 non-null  float64
 24  solarradiation   0 non-null      float64
 25  solarenergy      0 non-null      float64
 26  uvindex          38252 non-null  float64
 27  moonphase        38252 non-null  float64
 28  conditions       38252 non-null  object
 29  description      38252 non-null  object
 30  icon             38252 non-null  object
 31  stations         38252 non-null  object
 32  distance         38252 non-null  float64
 33  latitude.1       38252 non-null  float64
 34  longitude.1      38252 non-null  float64
 35  useCount         38252 non-null  int64
 36  id               38252 non-null  object
 37  name             38226 non-null  object
 38  quality          38252 non-null  int64
 39  contribution     38252 non-null  float64
dtypes: float64(28), int64(3), object(9)
memory usage: 11.7+ MB