In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./data/weather.csv')

In [3]:
df.head()

,queryCost,latitude,longitude,resolvedAddress,address,timezone,tzoffset,feelslikemax,feelslikemin,feelslike,...,pressure,cloudcover,visibility,solarradiation,solarenergy,uvindex,moonphase,conditions,description,icon
0,1,32.5625,107.4500,"32.5625,107.45","32.5625,107.45",Asia/Shanghai,8.00,90.7,76.0,82.7,...,1006.9,63.1,10.7,NaN,NaN,0.0,0.00,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day
1,1,45.4200,-122.6630,"45.42,-122.663","45.42,-122.663",America/Los_Angeles,-8.00,41.4,23.7,35.0,...,1010.4,56.2,9.1,NaN,NaN,0.0,0.14,"Rain, Partially cloudy",Partly cloudy throughout the day with a chance...,rain
2,1,-11.1295,-75.3587,"-11.1295,-75.3587","-11.1295,-75.3587",America/Lima,-5.00,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN
3,1,28.8378,81.7080,"28.8378,81.708","28.8378,81.708",Asia/Kathmandu,5.75,74.9,74.9,74.9,...,996.4,60.0,3.1,NaN,NaN,0.0,0.37,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day
4,1,10.3336,123.8978,"10.3336,123.8978","10.3336,123.8978",Asia/Manila,8.00,105.1,75.2,88.7,...,1008.0,88.6,6.1,NaN,NaN,0.0,0.33,"Rain, Partially cloudy",Partly cloudy throughout the day with rain.,rain

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11036 entries, 0 to 11035
Data columns (total 31 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   queryCost        11036 non-null  int64
 1   latitude         11036 non-null  float64
 2   longitude        11036 non-null  float64
 3   resolvedAddress  11036 non-null  object
 4   address          11036 non-null  object
 5   timezone         11036 non-null  object
 6   tzoffset         11036 non-null  float64
 7   feelslikemax     11004 non-null  float64
 8   feelslikemin     11004 non-null  float64
 9   feelslike        10317 non-null  float64
 10  dew              10282 non-null  float64
 11  humidity         10282 non-null  float64
 12  precip           10320 non-null  float64
 13  precipprob       541 non-null    float64
 14  precipcover      11007 non-null  float64
 15  preciptype       0 non-null      float64
 16  snow             1470 non-null   float64
 17  snowdepth        1657 non-null   float64
 18  windgust         3846 non-null   float64
 19  windspeed        10295 non-null  float64
 20  winddir          9773 non-null   float64
 21  pressure         8570 non-null   float64
 22  cloudcover       10320 non-null  float64
 23  visibility       10228 non-null  float64
 24  solarradiation   0 non-null      float64
 25  solarenergy      0 non-null      float64
 26  uvindex          9779 non-null   float64
 27  moonphase        11036 non-null  float64
 28  conditions       10320 non-null  object
 29  description      9779 non-null   object
 30  icon             10320 non-null  object
dtypes: float64(24), int64(1), object(6)
memory usage: 2.6+ MB