In [1]:
import pandas as pd
import numpy as np

In [2]:
df_weather = pd.read_csv('data/weather.csv')
df_weather

,queryCost,latitude,longitude,resolvedAddress,address,timezone,tzoffset,feelslikemax,feelslikemin,feelslike,...,icon,stations,distance,latitude.1,longitude.1,useCount,id,name,quality,contribution
0,1,32.56250,107.450000,"32.5625,107.45","32.5625,107.45",Asia/Shanghai,8.0,90.7,76.0,82.7,...,partly-cloudy-day,57127099999,68354.0,33.067,107.033,0,57127099999,"HANZHONG, CH",67,0.0
1,1,32.56250,107.450000,"32.5625,107.45","32.5625,107.45",Asia/Shanghai,8.0,90.7,76.0,82.7,...,partly-cloudy-day,57237099999,77810.0,32.067,108.033,0,57237099999,"WANYUAN, CH",65,0.0
2,1,45.42000,-122.663000,"45.42,-122.663","45.42,-122.663",America/Los_Angeles,-8.0,41.4,23.7,35.0,...,rain,72695994281,20805.0,45.249,-122.769,0,72695994281,"AURORA STATE AIRPORT, OR US",100,0.0
3,1,45.42000,-122.663000,"45.42,-122.663","45.42,-122.663",America/Los_Angeles,-8.0,41.4,23.7,35.0,...,rain,72698024229,20018.0,45.596,-122.609,0,72698024229,"PORTLAND INTERNATIONAL AIRPORT, OR US",100,0.0
4,1,45.42000,-122.663000,"45.42,-122.663","45.42,-122.663",America/Los_Angeles,-8.0,41.4,23.7,35.0,...,rain,72791894298,22358.0,45.621,-122.657,0,72791894298,"VANCOUVER PEARSON AIRPORT, WA US",100,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38247,1,17.46563,78.356505,"17.46562972,78.35650524","17.46562972,78.35650524",Asia/Kolkata,5.5,93.2,60.4,80.4,...,clear-day,43128599999,26642.0,17.233,78.417,0,43128599999,"HYDERABAD INTERNATIONAL AIRPORT, IN",46,0.0
38248,1,17.46563,78.356505,"17.46562972,78.35650524","17.46562972,78.35650524",Asia/Kolkata,5.5,93.2,60.4,80.4,...,clear-day,VOHY,12177.0,17.450,78.470,0,VOHY,VOHY,27,0.0
38249,1,17.46563,78.356505,"17.46562972,78.35650524","17.46562972,78.35650524",Asia/Kolkata,5.5,93.2,60.4,80.4,...,clear-day,VOHS,27368.0,17.230,78.430,0,VOHS,VOHS,45,0.0
38250,1,17.46563,78.356505,"17.46562972,78.35650524","17.46562972,78.35650524",Asia/Kolkata,5.5,93.2,60.4,80.4,...,clear-day,43128099999,11204.0,17.452,78.461,0,43128099999,"BEGUMPET AIRPORT, IN",85,0.0
38251,1,17.46563,78.356505,"17.46562972,78.35650524","17.46562972,78.35650524",Asia/Kolkata,5.5,93.2,60.4,80.4,...,clear-day,43083099999,65745.0,18.050,78.267,0,43083099999,"MEDAK, IN",54,0.0

In [4]:
df_weather.columns

Index(['queryCost', 'latitude', 'longitude', 'resolvedAddress', 'address',
       'timezone', 'tzoffset', 'feelslikemax', 'feelslikemin', 'feelslike',
       'dew', 'humidity', 'precip', 'precipprob', 'precipcover', 'preciptype',
       'snow', 'snowdepth', 'windgust', 'windspeed', 'winddir', 'pressure',
       'cloudcover', 'visibility', 'solarradiation', 'solarenergy', 'uvindex',
       'moonphase', 'conditions', 'description', 'icon', 'stations',
       'distance', 'latitude.1', 'longitude.1', 'useCount', 'id', 'name',
       'quality', 'contribution'],
      dtype='object')

In [3]:
df_original = pd.read_csv('data/GLC.csv')
df_original

,Unnamed: 0,event_id,event_date,event_title,event_description,location_description,location_accuracy,landslide_category,landslide_trigger,landslide_size,...,fatality_count,injury_count,storm_name,country_name,admin_division_name,admin_division_population,gazeteer_closest_point,gazeteer_distance,longitude,latitude
0,0,684,2008-08-01 00:00:00,"Sigou Village, Loufan County, Shanxi Province","occurred early in morning, 11 villagers buried...","Sigou Village, Loufan County, Shanxi Province",unknown,landslide,rain,large,...,11.0,NaN,NaN,China,Shaanxi,0.0,Jingyang,41.02145,107.450000,32.562500
1,1,956,2009-01-02 02:00:00,"Lake Oswego, Oregon",Hours of heavy rain are to blame for an overni...,"Lake Oswego, Oregon",5km,mudslide,downpour,small,...,0.0,NaN,NaN,United States,Oregon,36619.0,Lake Oswego,0.60342,-122.663000,45.420000
2,2,973,2007-01-19 00:00:00,"San Ramon district, 195 miles northeast of the...",(CBS/AP) At least 10 people died and as many a...,"San Ramon district, 195 miles northeast of the...",10km,landslide,downpour,large,...,10.0,NaN,NaN,Peru,Junín,14708.0,San Ramón,0.85548,-75.358700,-11.129500
3,3,1067,2009-07-31 00:00:00,Dailekh district,"One person was killed in Dailekh district, pol...",Dailekh district,unknown,landslide,monsoon,medium,...,1.0,NaN,NaN,Nepal,Mid Western,20908.0,Dailekh,0.75395,81.708000,28.837800
4,4,2603,2010-10-16 12:00:00,sitio Bakilid in barangay Lahug,Another landslide in sitio Bakilid in barangay...,sitio Bakilid in barangay Lahug,5km,landslide,tropical_cyclone,medium,...,0.0,NaN,Supertyphoon Juan (Megi),Philippines,Central Visayas,798634.0,Cebu City,2.02204,123.897800,10.333600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11028,11028,11109,2017-04-01 13:34:00,Major landslide in Banaran,Landslide exacerbated by deforestation and bad...,"Banaran, Ponorogo, Jawa Timur, Indonesia",5km,landslide,rain,medium,...,27.0,0.0,NaN,Indonesia,NaN,NaN,NaN,NaN,111.679944,-7.853409
11029,11029,10845,2017-03-25 17:32:00,Barnari Sigdi Landslide,Two teenage girls died after they were buried ...,"Barnari Sigdi area, Tehsil Mughalmaidan, Kisht...",5km,landslide,other,small,...,2.0,0.0,NaN,India,NaN,NaN,NaN,NaN,75.680611,33.403080
11030,11030,10973,2016-12-15 05:00:00,Landslide at Pub Sarania Hill,An octogenarian was killed when a sudden lands...,"Pub Sarania Hill, Guwahati, Assam, India",1km,landslide,unknown,small,...,1.0,0.0,NaN,India,NaN,NaN,NaN,NaN,91.772042,26.181606
11031,11031,10901,2017-04-29 19:03:00,Mayor landslide at Ayu village,Landslide triggered by heavy rainfall buried 1...,"Ayu, Ozgon, Osh, Kyrgyzstan",1km,translational_slide,downpour,large,...,24.0,NaN,NaN,Kyrgyzstan,NaN,NaN,NaN,NaN,73.472379,40.886395
11032,11032,10949,2017-03-13 14:32:00,Kondapur Commercial Complex Construction Mudslide,A mudslide at an under-construction commercial...,"Hyderabad, Rangareddy, Telangana",1km,mudslide,construction,small,...,2.0,0.0,NaN,India,NaN,NaN,NaN,NaN,78.356505,17.465630